name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:

    runs-on: ubuntu-latest

    steps:

      # Checkout source code
      - name: Checkout Project
        uses: actions/checkout@v4


      # Python setup
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      # Install Flet
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet==0.85.3


      # Install exact Flutter version required by Flet
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.7"
          channel: stable
          cache: true


      # Accept Android licenses
      - name: Accept Android Licenses
        run: |
          yes | flutter doctor --android-licenses || true


      # Check Flutter
      - name: Flutter Doctor
        run: |
          flutter doctor -v


      # Build APK
      - name: Build APK
        env:
          CI: true
        run: |
          flet build apk --verbose --no-rich-output


      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OrbitDrivingSchool-APK
          path: build/apk/*.apk
          if-no-files-found: error
